version: '3.8'

services:
  oracle-23ai:
    image: gvenzl/oracle-free:23-slim
    container_name: oracle-23ai
    ports:
      - "8521:1521"
    environment:
      - ORACLE_PASSWORD=SysPassword1
    volumes:
      - oracle_data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "system/SysPassword1@//localhost/freepdb1", "AS", "SYSDBA"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  oracle_data:
